"""add image_width and image_height to RequestLog

Revision ID: 0f82f1ed53b0
Revises: 7c04de341b8b
Create Date: 2025-12-21 17:58:11.632570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f82f1ed53b0'
down_revision: Union[str, Sequence[str], None] = '7c04de341b8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('image_width', sa.Integer(), nullable=True))
    op.add_column('request_logs', sa.Column('image_height', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'image_height')
    op.drop_column('request_logs', 'image_width')
    # ### end Alembic commands ###
