// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteHistoryHistoryDeleteData, DeleteHistoryHistoryDeleteResponses, ForwardForwardPostData, ForwardForwardPostErrors, ForwardForwardPostResponses, ForwardMultipleForwardMultiplePostData, ForwardMultipleForwardMultiplePostErrors, ForwardMultipleForwardMultiplePostResponses, GetStatsStatsGetData, GetStatsStatsGetResponses, ReadHistoryHistoryGetData, ReadHistoryHistoryGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Delete History
 */
export const deleteHistoryHistoryDelete = <ThrowOnError extends boolean = false>(options?: Options<DeleteHistoryHistoryDeleteData, ThrowOnError>) => (options?.client ?? client).delete<DeleteHistoryHistoryDeleteResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/history',
    ...options
});

/**
 * Read History
 */
export const readHistoryHistoryGet = <ThrowOnError extends boolean = false>(options?: Options<ReadHistoryHistoryGetData, ThrowOnError>) => (options?.client ?? client).get<ReadHistoryHistoryGetResponses, unknown, ThrowOnError>({ url: '/history', ...options });

/**
 * Get Stats
 */
export const getStatsStatsGet = <ThrowOnError extends boolean = false>(options?: Options<GetStatsStatsGetData, ThrowOnError>) => (options?.client ?? client).get<GetStatsStatsGetResponses, unknown, ThrowOnError>({ url: '/stats', ...options });

/**
 * Forward
 */
export const forwardForwardPost = <ThrowOnError extends boolean = false>(options: Options<ForwardForwardPostData, ThrowOnError>) => (options.client ?? client).post<ForwardForwardPostResponses, ForwardForwardPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/forward',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Forward Multiple
 */
export const forwardMultipleForwardMultiplePost = <ThrowOnError extends boolean = false>(options: Options<ForwardMultipleForwardMultiplePostData, ThrowOnError>) => (options.client ?? client).post<ForwardMultipleForwardMultiplePostResponses, ForwardMultipleForwardMultiplePostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/forwardMultiple',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});
