// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_forward_forward_post
 */
export type BodyForwardForwardPost = {
    /**
     * Image
     */
    image: Blob | File;
};

/**
 * Body_forward_multiple_forwardMultiple_post
 */
export type BodyForwardMultipleForwardMultiplePost = {
    /**
     * Images
     */
    images: Array<Blob | File>;
};

/**
 * Body_login_auth_login_post
 */
export type BodyLoginAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * DebugPayload
 */
export type DebugPayload = {
    /**
     * Hog
     */
    hog: Array<number>;
    /**
     * Processed Image
     */
    processed_image: string;
    /**
     * Hog Image
     */
    hog_image?: string | null;
};

/**
 * DeleteHistoryResponse
 */
export type DeleteHistoryResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * DeleteUserResponse
 */
export type DeleteUserResponse = {
    /**
     * Message
     */
    message: string;
};

/**
 * ForwardImageResponse
 */
export type ForwardImageResponse = {
    /**
     * Filename
     */
    filename?: string | null;
    /**
     * Prediction
     */
    prediction?: string | number | number | null;
    /**
     * Confidence
     */
    confidence?: number | null;
    /**
     * Image Base64
     */
    image_base64: string;
    debug?: DebugPayload | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageStats
 */
export type ImageStats = {
    /**
     * Mean Width
     */
    mean_width: number;
    /**
     * Mean Height
     */
    mean_height: number;
    /**
     * Count
     */
    count: number;
};

/**
 * PredictionResponse
 */
export type PredictionResponse = {
    /**
     * Study Id
     */
    study_id: string;
    /**
     * Filenames
     */
    filenames: Array<string>;
    /**
     * Prediction
     */
    prediction?: string | number | number | null;
    /**
     * Confidence
     */
    confidence?: number | null;
    debug?: DebugPayload | null;
};

/**
 * ProcessingTimeStats
 */
export type ProcessingTimeStats = {
    /**
     * Mean Ms
     */
    mean_ms: number;
    /**
     * P50 Ms
     */
    p50_ms: number;
    /**
     * P95 Ms
     */
    p95_ms: number;
    /**
     * P99 Ms
     */
    p99_ms: number;
};

/**
 * RegisterRequest
 */
export type RegisterRequest = {
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
};

/**
 * RegisterResponse
 */
export type RegisterResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Role
     */
    role: string;
};

/**
 * RequestLogEntry
 */
export type RequestLogEntry = {
    /**
     * Id
     */
    id: number;
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Input Meta
     */
    input_meta?: string | null;
    /**
     * Duration
     */
    duration?: number | null;
    /**
     * Result
     */
    result?: string | null;
    /**
     * Status
     */
    status?: number | null;
};

/**
 * StatsResponse
 */
export type StatsResponse = {
    processing_time: ProcessingTimeStats;
    image_stats: ImageStats;
};

/**
 * TokenResponse
 */
export type TokenResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
    /**
     * Username
     */
    username: string;
    /**
     * Role
     */
    role: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type LoginAuthLoginPostData = {
    body: BodyLoginAuthLoginPost;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type LoginAuthLoginPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginAuthLoginPostError = LoginAuthLoginPostErrors[keyof LoginAuthLoginPostErrors];

export type LoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: TokenResponse;
};

export type LoginAuthLoginPostResponse = LoginAuthLoginPostResponses[keyof LoginAuthLoginPostResponses];

export type RegisterAuthRegisterPostData = {
    body: RegisterRequest;
    headers?: {
        /**
         * Authorization
         */
        authorization?: string | null;
    };
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterAuthRegisterPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterAuthRegisterPostError = RegisterAuthRegisterPostErrors[keyof RegisterAuthRegisterPostErrors];

export type RegisterAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    200: RegisterResponse;
};

export type RegisterAuthRegisterPostResponse = RegisterAuthRegisterPostResponses[keyof RegisterAuthRegisterPostResponses];

export type ListUsersAuthUsersGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/users';
};

export type ListUsersAuthUsersGetResponses = {
    /**
     * Response List Users Auth Users Get
     *
     * Successful Response
     */
    200: Array<UserResponse>;
};

export type ListUsersAuthUsersGetResponse = ListUsersAuthUsersGetResponses[keyof ListUsersAuthUsersGetResponses];

export type DeleteUserAuthUsersUsernameDeleteData = {
    body?: never;
    path: {
        /**
         * Username
         */
        username: string;
    };
    query?: never;
    url: '/auth/users/{username}';
};

export type DeleteUserAuthUsersUsernameDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserAuthUsersUsernameDeleteError = DeleteUserAuthUsersUsernameDeleteErrors[keyof DeleteUserAuthUsersUsernameDeleteErrors];

export type DeleteUserAuthUsersUsernameDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteUserResponse;
};

export type DeleteUserAuthUsersUsernameDeleteResponse = DeleteUserAuthUsersUsernameDeleteResponses[keyof DeleteUserAuthUsersUsernameDeleteResponses];

export type DeleteHistoryHistoryDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/history';
};

export type DeleteHistoryHistoryDeleteResponses = {
    /**
     * Successful Response
     */
    200: DeleteHistoryResponse;
};

export type DeleteHistoryHistoryDeleteResponse = DeleteHistoryHistoryDeleteResponses[keyof DeleteHistoryHistoryDeleteResponses];

export type ReadHistoryHistoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/history';
};

export type ReadHistoryHistoryGetResponses = {
    /**
     * Response Read History History Get
     *
     * Successful Response
     */
    200: Array<RequestLogEntry>;
};

export type ReadHistoryHistoryGetResponse = ReadHistoryHistoryGetResponses[keyof ReadHistoryHistoryGetResponses];

export type GetStatsStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetStatsStatsGetResponses = {
    /**
     * Successful Response
     */
    200: StatsResponse;
};

export type GetStatsStatsGetResponse = GetStatsStatsGetResponses[keyof GetStatsStatsGetResponses];

export type ForwardForwardPostData = {
    body: BodyForwardForwardPost;
    headers?: {
        /**
         * X-Debug
         */
        'X-Debug'?: boolean;
    };
    path?: never;
    query?: never;
    url: '/forward';
};

export type ForwardForwardPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForwardForwardPostError = ForwardForwardPostErrors[keyof ForwardForwardPostErrors];

export type ForwardForwardPostResponses = {
    /**
     * Successful Response
     */
    200: ForwardImageResponse;
};

export type ForwardForwardPostResponse = ForwardForwardPostResponses[keyof ForwardForwardPostResponses];

export type ForwardMultipleForwardMultiplePostData = {
    body: BodyForwardMultipleForwardMultiplePost;
    headers: {
        /**
         * X-Study-Ids
         */
        'X-Study-Ids': string;
        /**
         * X-Debug
         */
        'X-Debug'?: boolean;
    };
    path?: never;
    query?: never;
    url: '/forwardMultiple';
};

export type ForwardMultipleForwardMultiplePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForwardMultipleForwardMultiplePostError = ForwardMultipleForwardMultiplePostErrors[keyof ForwardMultipleForwardMultiplePostErrors];

export type ForwardMultipleForwardMultiplePostResponses = {
    /**
     * Response Forward Multiple Forwardmultiple Post
     *
     * Successful Response
     */
    200: Array<PredictionResponse>;
};

export type ForwardMultipleForwardMultiplePostResponse = ForwardMultipleForwardMultiplePostResponses[keyof ForwardMultipleForwardMultiplePostResponses];
