// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * Body_forward_forward_post
 */
export type BodyForwardForwardPost = {
    /**
     * Image
     */
    image: Blob | File;
};

/**
 * Body_forward_multiple_forwardMultiple_post
 */
export type BodyForwardMultipleForwardMultiplePost = {
    /**
     * Images
     */
    images: Array<Blob | File>;
};

/**
 * DebugPayload
 */
export type DebugPayload = {
    /**
     * Hog
     */
    hog: Array<number>;
    /**
     * Processed Image
     */
    processed_image: string;
    /**
     * Hog Image
     */
    hog_image?: string | null;
};

/**
 * ForwardImageResponse
 */
export type ForwardImageResponse = {
    /**
     * Filename
     */
    filename?: string | null;
    /**
     * Prediction
     */
    prediction?: string | number | number | null;
    /**
     * Confidence
     */
    confidence?: number | null;
    /**
     * Image Base64
     */
    image_base64: string;
    debug?: DebugPayload | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PredictionResponse
 */
export type PredictionResponse = {
    /**
     * Study Id
     */
    study_id: string;
    /**
     * Filenames
     */
    filenames: Array<string>;
    /**
     * Prediction
     */
    prediction?: string | number | number | null;
    /**
     * Confidence
     */
    confidence?: number | null;
    debug?: DebugPayload | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type DeleteHistoryHistoryDeleteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/history';
};

export type DeleteHistoryHistoryDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadHistoryHistoryGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/history';
};

export type ReadHistoryHistoryGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetStatsStatsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/stats';
};

export type GetStatsStatsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ForwardForwardPostData = {
    body: BodyForwardForwardPost;
    headers?: {
        /**
         * X-Debug
         */
        'X-Debug'?: boolean;
    };
    path?: never;
    query?: {
        /**
         * As Gray
         */
        as_gray?: unknown;
    };
    url: '/forward';
};

export type ForwardForwardPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForwardForwardPostError = ForwardForwardPostErrors[keyof ForwardForwardPostErrors];

export type ForwardForwardPostResponses = {
    /**
     * Successful Response
     */
    200: ForwardImageResponse;
};

export type ForwardForwardPostResponse = ForwardForwardPostResponses[keyof ForwardForwardPostResponses];

export type ForwardMultipleForwardMultiplePostData = {
    body: BodyForwardMultipleForwardMultiplePost;
    headers: {
        /**
         * X-Study-Ids
         */
        'X-Study-Ids': string;
        /**
         * X-Debug
         */
        'X-Debug'?: boolean;
    };
    path?: never;
    query?: {
        /**
         * As Gray
         */
        as_gray?: unknown;
    };
    url: '/forwardMultiple';
};

export type ForwardMultipleForwardMultiplePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ForwardMultipleForwardMultiplePostError = ForwardMultipleForwardMultiplePostErrors[keyof ForwardMultipleForwardMultiplePostErrors];

export type ForwardMultipleForwardMultiplePostResponses = {
    /**
     * Response Forward Multiple Forwardmultiple Post
     *
     * Successful Response
     */
    200: Array<PredictionResponse>;
};

export type ForwardMultipleForwardMultiplePostResponse = ForwardMultipleForwardMultiplePostResponses[keyof ForwardMultipleForwardMultiplePostResponses];
